#!/bin/bash

# CONSTANTS / DEFAULT VALUES
readonly version=1.0
readonly K_DEFAULT_DEVICE_NB=0
readonly K_LED_OFF=0
readonly K_LED_ON=1
readonly K_VLC_PARAM_INFINITE_LOOP_ACTIVATED=--loop
readonly K_VLC_PARAM_INFINITE_LOOP_DEACTIVATED=
readonly K_DEFAULT_WIDTH=1280
readonly K_DEFAULT_HEIGHT=720
readonly K_DEFAULT_HTTP_PORT=8099
readonly K_DEFAULT_EACH_MOVIE_DURATION_SEC=120
readonly K_DEFAULT_GLOBAL_RECORD_TIMEOUT=10800
readonly K_DEFAULT_FILE_NAME_MASK=Webcam_Stream_Record
readonly K_DEFAULT_FPS=30

# Set the notification email recipient via environment variable before running.
# Example: export WEBCAM_STREAM_MAIL_TO=you@example.com
readonly K_DEFAULT_MAIL_RECIPIENT="${WEBCAM_STREAM_MAIL_TO:-}"


#
# Uses Argbash
#
# ARG_HELP([This command allows to trigger a VLC video HTTP stream, and optionnaly record it to MP4 files. User is able to choose record duration and split movies duration.])

# ARG_POSITIONAL_SINGLE([video-device-number],[The video capture device number (webcam) that can be found in /dev. Ex: Put 0 if your device is /dev/video0],[])
# ARG_POSITIONAL_SINGLE([http-port],[The HTTP port to be used by VLC to provide the video stream from the video capture device.],[$K_DEFAULT_HTTP_PORT])

# ARG_OPTIONAL_SINGLE([output-videos-directory],[o],[Directory in which the VLC videos are stored. It means that the video stream will be recorded in addition to HTTP stream. Full path expected.])
# ARG_OPTIONAL_SINGLE([video-file-name-mask],[m],[Videos files record name. Files will be generated as: 1970-12-31_%00h00m00s_<yourvalue> ],[$K_DEFAULT_FILE_NAME_MASK])

# ARG_OPTIONAL_SINGLE([video-files-split-after],[],[Defines the unitary VLC record file duration in seconds. WARNING: Only necessary when output-videos-directory is used],[$K_DEFAULT_EACH_MOVIE_DURATION_SEC])
# ARG_OPTIONAL_SINGLE([stop-stream-after],[],[Defines the delay after which the VLC record will stop in seconds. WARNING: Only necessary when output-videos-directory is used],[$K_DEFAULT_GLOBAL_RECORD_TIMEOUT])

# ARG_OPTIONAL_BOOLEAN([use-msmtp],[],[Send mail using msmtp indicating start of record. Set recipient via WEBCAM_STREAM_MAIL_TO env var.])
# ARG_OPTIONAL_BOOLEAN([with-audio],[],[Enable microphone/audio capture in stream and recordings. Off by default.])
# ARG_OPTIONAL_BOOLEAN([force-led-on],[],[Forces the Logitech C920 LED to be on.])

# ARG_OPTIONAL_SINGLE([video-width],[],[Force video format width. Use at your own risk.],[$K_DEFAULT_WIDTH])
# ARG_OPTIONAL_SINGLE([video-height],[],[Force video format height. Use at your own risk.],[$K_DEFAULT_HEIGHT])


# ARG_OPTIONAL_INCREMENTAL([verbose],[V],[Console output verbosity. Controls both this command and underlying VLC verbosity.])
# ARG_VERSION([echo Raspi VLC Webcam Stream v$version (designed for Logitech C920)])

# ARGBASH_GO()
# needed because of Argbash --> m4_ignore([
### START OF CODE GENERATED BY Argbash v2.6.1 one line above ###
# Argbash is a bash code generator used to get arguments parsing right.
# Argbash is FREE SOFTWARE, see https://argbash.io for more info
# Generated online by https://argbash.io/generate

# When called, the process ends.
# Args:
#   $1: The exit message (print to stderr)
#   $2: The exit code (default is 1)
# if env var _PRINT_HELP is set to 'yes', the usage is print to stderr (prior to )
# Example:
#   test -f "$_arg_infile" || _PRINT_HELP=yes die "Can't continue, have to supply file as an argument, got '$_arg_infile'" 4
die()
{
    local _ret=$2
    test -n "$_ret" || _ret=1
    test "$_PRINT_HELP" = yes && print_help >&2
    echo "$1" >&2
    exit ${_ret}
}

# Function that evaluates whether a value passed to it begins by a character
# that is a short option of an argument the script knows about.
# This is required in order to support getopts-like short options grouping.
begins_with_short_option()
{
    local first_option all_short_options
    all_short_options='homVv'
    first_option="${1:0:1}"
    test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
}



# THE DEFAULTS INITIALIZATION - POSITIONALS
# The positional args array has to be reset before the parsing, because it may already be defined
# - for example if this script is sourced by an argbash-powered script.
_positionals=()
_arg_http_port="$K_DEFAULT_HTTP_PORT"
# THE DEFAULTS INITIALIZATION - OPTIONALS
_arg_output_videos_directory=
_arg_video_file_name_mask="${K_DEFAULT_FILE_NAME_MASK}"
_arg_video_files_split_after="$K_DEFAULT_EACH_MOVIE_DURATION_SEC"
_arg_stop_stream_after="$K_DEFAULT_GLOBAL_RECORD_TIMEOUT"
_arg_use_ssmtp="off"
_arg_with_audio="off"
_arg_force_led_on="off"
_arg_video_width="${K_DEFAULT_WIDTH}"
_arg_video_height="$K_DEFAULT_HEIGHT"
_arg_verbose=0

# Function that prints general usage of the script.
print_help ()
{
    printf '\n%s\n' "This command allows to trigger a VLC video HTTP stream, and optionnaly record it to MP4 files."
    printf '\n%s\n\n\n' "User is able to choose record duration and split movies duration."
    printf 'Usage: %s [-h|--help] [-o|--output-videos-directory <arg>] [-m|--video-file-name-mask <arg>] [--video-files-split-after <arg>] [--stop-stream-after <arg>] [--(no-)use-msmtp] [--(no-)force-led-on] [--video-width <arg>] [--video-height <arg>] [-V|--verbose] [-v|--version] <video-device-number> [<http-port>]\n\n\n' "$0"
    printf '\t%s\n' "<video-device-number>: The video capture device number (webcam) that can be found in /dev. Ex: Put 0 if your device is /dev/video0"
    printf '\t%s\n' "<http-port>: The HTTP port to be used by VLC to provide the video stream from the video capture device. Default will be 8099 (default: '${K_DEFAULT_HTTP_PORT}')"
    printf '\t%s\n' "-h,--help: Prints help"
    printf '\t%s\n' "-o,--output-videos-directory: Directory in which the VLC videos are stored. It means that the video stream will be recorded in addition to HTTP stream. Full path expected. (no default)"
    printf '\t%s\n' "-m,--video-file-name-mask: Videos files record name. Files will be generated as: 1970-12-31_%00h00m00s_<yourvalue>  (default: '$K_DEFAULT_FILE_NAME_MASK')"
    printf '\t%s\n' "--video-files-split-after: Defines the unitary VLC record file duration in seconds. WARNING: Only necessary when output-videos-directory is used (default: '$K_DEFAULT_EACH_MOVIE_DURATION_SEC')"
    printf '\t%s\n' "--stop-stream-after: Defines the delay after which the VLC record will stop in seconds. WARNING: Only necessary when output-videos-directory is used (default: '$K_DEFAULT_GLOBAL_RECORD_TIMEOUT')"
    printf '\t%s\n' "--use-msmtp,--no-use-msmtp: Send mail using msmtp indicating start of record. Set recipient via WEBCAM_STREAM_MAIL_TO env var. (off by default)"
    printf '\t%s\n' "--with-audio,--no-with-audio: Enable microphone/audio capture in stream and recordings. (off by default)"
    printf '\t%s\n' "--force-led-on,--no-force-led-on: Forces the Logitech C920 LED to be on. (off by default)"
    printf '\t%s\n' "--video-width: Force video format width. Use at your own risk. (default: '$K_DEFAULT_WIDTH')"
    printf '\t%s\n' "--video-height: Force video format height. Use at your own risk. (default: '$K_DEFAULT_HEIGHT')"
    printf '\t%s\n' "-V,--verbose: Console output verbosity. Controls both this command and underlying VLC verbosity."
    printf '\t%s\n' "-v,--version: Prints version"
}

# The parsing of the command-line
parse_commandline ()
{
    while test $# -gt 0
    do
        _key="$1"
        case "$_key" in
            -h|--help)
                print_help
                exit 0
                ;;
            -h*)
                print_help
                exit 0
                ;;
            -o|--output-videos-directory)
                test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
                _arg_output_videos_directory="$2"
                shift
                ;;
            --output-videos-directory=*)
                _arg_output_videos_directory="${_key##--output-videos-directory=}"
                ;;
            -o*)
                _arg_output_videos_directory="${_key##-o}"
                ;;
            -m|--video-file-name-mask)
                test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
                _arg_video_file_name_mask="$2"
                shift
                ;;
            --video-file-name-mask=*)
                _arg_video_file_name_mask="${_key##--video-file-name-mask=}"
                ;;
            -m*)
                _arg_video_file_name_mask="${_key##-m}"
                ;;
            --video-files-split-after)
                test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
                _arg_video_files_split_after="$2"
                shift
                ;;
            --video-files-split-after=*)
                _arg_video_files_split_after="${_key##--video-files-split-after=}"
                ;;
            --stop-stream-after)
                test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
                _arg_stop_stream_after="$2"
                shift
                ;;
            --stop-stream-after=*)
                _arg_stop_stream_after="${_key##--stop-stream-after=}"
                ;;
            --no-use-msmtp|--use-msmtp)
                _arg_use_ssmtp="on"
                test "${1:0:5}" = "--no-" && _arg_use_ssmtp="off"
                ;;
            --no-with-audio|--with-audio)
                _arg_with_audio="on"
                test "${1:0:5}" = "--no-" && _arg_with_audio="off"
                ;;
            --no-force-led-on|--force-led-on)
                _arg_force_led_on="on"
                test "${1:0:5}" = "--no-" && _arg_force_led_on="off"
                ;;
            --video-width)
                test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
                _arg_video_width="$2"
                shift
                ;;
            --video-width=*)
                _arg_video_width="${_key##--video-width=}"
                ;;
            --video-height)
                test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
                _arg_video_height="$2"
                shift
                ;;
            --video-height=*)
                _arg_video_height="${_key##--video-height=}"
                ;;
            -V|--verbose)
                _arg_verbose=$((_arg_verbose + 1))
                ;;
            -V*)
                _arg_verbose=$((_arg_verbose + 1))
                _next="${_key##-V}"
                if test -n "$_next" -a "$_next" != "$_key"
                then
                    begins_with_short_option "$_next" && shift && set -- "-V" "-${_next}" "$@" || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
                fi
                ;;
            -v|--version)
                echo "Raspi VLC Webcam Stream v$version (designed for Logitech C920)"
                exit 0
                ;;
            -v*)
                echo "Raspi VLC Webcam Stream v$version (designed for Logitech C920)"
                exit 0
                ;;
            *)
                _positionals+=("$1")
                ;;
        esac
        shift
    done
}


# Check that we receive expected amount positional arguments.
# Return 0 if everything is OK, 1 if we have too little arguments
# and 2 if we have too much arguments
handle_passed_args_count ()
{
    _required_args_string="'video-device-number'"
    test ${#_positionals[@]} -ge 1 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require between 1 and 2 (namely: $_required_args_string), but got only ${#_positionals[@]}." 1
    test ${#_positionals[@]} -le 2 || _PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect between 1 and 2 (namely: $_required_args_string), but got ${#_positionals[@]} (the last one was: '${_positionals[*]: -1}')." 1
}

# Take arguments that we have received, and save them in variables of given names.
# The 'eval' command is needed as the name of target variable is saved into another variable.
assign_positional_args ()
{
    _positional_names=('_arg_video_device_number' '_arg_http_port' )

    for (( ii = 0; ii < ${#_positionals[@]}; ii++))
    do
        eval "${_positional_names[ii]}=\${_positionals[ii]}" || die "Error during argument parsing, possibly an Argbash bug." 1
    done
}

parse_commandline "$@"
handle_passed_args_count
assign_positional_args

### END OF CODE GENERATED BY Argbash (sortof) ### ])
# [ <-- needed because of Argbash



WIDTH=${_arg_video_width}
HEIGHT=${_arg_video_height}
LED_COMMAND=

VIDEO_DEVICE_NB=${_arg_video_device_number}

EACH_MOVIE_DURATION_SEC=${_arg_video_files_split_after}
GLOBAL_RECORD_TIMEOUT=${_arg_stop_stream_after}

FILE_NAME_MASK=${_arg_video_file_name_mask}
MOVIES_FOLDER=${_arg_output_videos_directory}

HTTP_PORT=${_arg_http_port}


#ERROR CODES
readonly ERROR_MAIL=99
readonly ERROR_V4L2_CTL=98
readonly ERROR_VLC=97
readonly ERROR_FOLDER_DOES_NOT_EXIST=2
readonly ERROR_WEBCAM_DOES_NOT_EXIST=1

WEBCAM_DEVICE=/dev/video${VIDEO_DEVICE_NB}


function VLC_C920_STREAM {
	VIDEO_DEVICE_NB=$1
	HTTP_PORT=$2
	MOVIES_FOLDER=$3

	FILE_NAME_PATTERN="%Y-%m-%d_%Hh%Mm%Ss_${FILE_NAME_MASK}.mp4"
	VLC_FILE_DUPLICATE_ARG="standard{access=file,mux=mp4,dst='${MOVIES_FOLDER}/${FILE_NAME_PATTERN}'}"
	VLC_HTTP_DUPLICATE_ARG="standard{access=http,mux=ts,mime=video/ts,dst=:${HTTP_PORT}}"
	# C920 on this kernel exposes MJPG and YUYV only (no native H264 via UVC).
	# MJPG supports 1920x1080@30fps; YUYV tops out at 5fps at that resolution.
	# VLC transcodes MJPG → H264 using the RPi 4 BCM2835 hardware encoder via V4L2 M2M,
	# but the MJPG decode side is software/single-threaded and can't sustain 1080p30 in
	# real time on this SoC (falls behind ~0.6x realtime, backlog grows unbounded).
	# 1280x720@30fps is the default because it's the largest size that decodes in real
	# time (verified: mux lag stays <250ms indefinitely). Override via --video-width/
	# --video-height at your own risk of growing latency.
	# --sout-avcodec-codec selects the hw encoder; --sout-avcodec-keyint sets a 1 s keyframe
	# interval so clients can connect quickly without waiting for the default 10 s GOP.
	VLC_VIDEO_TRANSCODE="vcodec=h264,vb=4000,scale=1,venc=avcodec"
	MAIL_CMD=msmtp
	# VLC 3.x passes legacy MPEG avcodec options that the V4L2 M2M encoder doesn't support,
	# and always warns about missing GUI modules in headless mode. Filter both from stderr.
	VLC_STDERR_FILTER='no suitable interface module|globalhotkeys|dummy interface: using|Unknown option "(border_mask|noise_reduction|lmin|lmax|qsquish|rc_buffer_aggressivity)"'

	if [ "${_arg_with_audio}" != "off" ]; then
		VLC_INPUT_SLAVE=":input-slave=pulse://"
		VLC_SOUT_PREFIX="#transcode{${VLC_VIDEO_TRANSCODE},acodec=mp4a,ab=128,channels=2,samplerate=44100,threads=4,audio-sync=1}:"
	else
		VLC_INPUT_SLAVE=""
		VLC_SOUT_PREFIX="#transcode{${VLC_VIDEO_TRANSCODE}}:"
	fi
	VLC_PARAM_INFINITE_LOOP=${K_VLC_PARAM_INFINITE_LOOP_ACTIVATED}

	log INFO "Device:     /dev/video${VIDEO_DEVICE_NB}"
	log INFO "Resolution: ${WIDTH}x${HEIGHT} @ ${K_DEFAULT_FPS} fps"
	log INFO "HTTP port:  ${HTTP_PORT}"
	if [ -n "${MOVIES_FOLDER}" ] ; then
		log INFO "Mode:       stream + record | output=${MOVIES_FOLDER} split=${EACH_MOVIE_DURATION_SEC}s timeout=${GLOBAL_RECORD_TIMEOUT}s"
	else
		log INFO "Mode:       stream only"
	fi
	log INFO "Audio:      ${_arg_with_audio}"

	# Only require the mail tool when the feature is actually requested
	if [ "${_arg_use_ssmtp}" != "off" ] ; then
		checkCommandExists "${MAIL_CMD}" "${ERROR_MAIL}"
	fi
	checkCommandExists v4l2-ctl "${ERROR_V4L2_CTL}"
	checkCommandExists vlc "${ERROR_VLC}"

	if [ "${_arg_use_ssmtp}" != "off" ] ; then
		if [ -z "${K_DEFAULT_MAIL_RECIPIENT}" ] ; then
			displayErrorMessage "${ERROR_MAIL}" "No mail recipient set. Export WEBCAM_STREAM_MAIL_TO=your@email.com before running."
		fi
		echo -e "Starting VLC stream and record\nDate: $(date)\nVIDEO_DEVICE_NB: ${VIDEO_DEVICE_NB}\nDuration: ${GLOBAL_RECORD_TIMEOUT}\nVLC_PARAM_INFINITE_LOOP: ${VLC_PARAM_INFINITE_LOOP}\nFile duration: ${EACH_MOVIE_DURATION_SEC}" \
			| "${MAIL_CMD}" "${K_DEFAULT_MAIL_RECIPIENT}"
	fi

	if [ "${_arg_force_led_on}" != "off" ] ; then
		LED_COMMAND="${K_LED_ON}"
	else
		LED_COMMAND="${K_LED_OFF}"
	fi

	log INFO "Configuring camera controls"
	# led1_mode via v4l2-ctl works on older kernels/firmware; silently ignore on newer ones.
	v4l2-ctl -d "${VIDEO_DEVICE_NB}" --set-ctrl=led1_mode="${LED_COMMAND}" 2>/dev/null || true
	# C920 PRO (0x08e5) and other V3 firmware cameras expose the LED through a UVC
	# extension unit that is not wired up as a v4l2 control on kernel 6.x.
	# c920_led.py reaches it directly via UVCIOC_CTRL_QUERY.
	python3 "$(dirname "$0")/c920_led.py" "${VIDEO_DEVICE_NB}" "${LED_COMMAND}" 2>/dev/null || true
	# Disable dynamic framerate: the camera lowers FPS in low light to allow longer exposure,
	# which causes VLC to receive frames at inconsistent intervals and stutter.
	v4l2-ctl -d "${VIDEO_DEVICE_NB}" --set-ctrl=exposure_dynamic_framerate=0 2>/dev/null || true

	if [ -n "${MOVIES_FOLDER}" ] ; then
		if [ -d "${MOVIES_FOLDER}" ] ; then
			# Stream to HTTP and simultaneously record to split MP4 files.
			# --avcodec-hw=any    use RPi 4 VideoCore VI V4L2 M2M hardware codec where possible
			# --live-caching=0    no app-level input buffer; v4l2 kernel buffers are sufficient
			# pulse://            audio input via PipeWire's PulseAudio compat layer (Bookworm default),
			#                     replacing the brittle alsa://hw:1,0 hardware index
			log INFO "Starting VLC (stream + record, timeout=${GLOBAL_RECORD_TIMEOUT}s)"
			timeout "${GLOBAL_RECORD_TIMEOUT}"s \
			cvlc \
				--avcodec-hw=any \
				--sout-avcodec-codec=h264_v4l2m2m \
				--sout-avcodec-keyint=30 \
				--live-caching=0 \
				--sout-file-format \
				--run-time="${EACH_MOVIE_DURATION_SEC}" \
				"${VLC_PARAM_INFINITE_LOOP}" \
				"v4l2:///dev/video${VIDEO_DEVICE_NB}:chroma=MJPG:width=${WIDTH}:height=${HEIGHT}:fps=${K_DEFAULT_FPS}" \
				${VLC_INPUT_SLAVE:+"${VLC_INPUT_SLAVE}"} \
				--sout \
				"${VLC_SOUT_PREFIX}duplicate{dst=${VLC_FILE_DUPLICATE_ARG}:dst=${VLC_HTTP_DUPLICATE_ARG}}" \
				2> >(grep -Ev "${VLC_STDERR_FILTER}" >&2)
			vlc_exit=$?
			if [ "${vlc_exit}" -eq 124 ] ; then
				log INFO "VLC stopped after ${GLOBAL_RECORD_TIMEOUT}s timeout"
			elif [ "${vlc_exit}" -eq 0 ] ; then
				log INFO "VLC exited cleanly"
			else
				log WARN "VLC exited with code ${vlc_exit}"
			fi
		else
			msg="Folder ${MOVIES_FOLDER} passed in argument is invalid or does not exist. Aborting."
			displayErrorMessage "${ERROR_FOLDER_DOES_NOT_EXIST}" "$msg"
		fi
	else
		# Stream only — no timeout so the stream runs until manually stopped.
		log INFO "Starting VLC (stream only, Ctrl-C to stop)"
		cvlc \
			--avcodec-hw=any \
			--sout-avcodec-codec=h264_v4l2m2m \
			--sout-avcodec-keyint=30 \
			--live-caching=0 \
			"${VLC_PARAM_INFINITE_LOOP}" \
			"v4l2:///dev/video${VIDEO_DEVICE_NB}:chroma=MJPG:width=${WIDTH}:height=${HEIGHT}:fps=${K_DEFAULT_FPS}" \
			${VLC_INPUT_SLAVE:+"${VLC_INPUT_SLAVE}"} \
			--sout \
			"${VLC_SOUT_PREFIX}${VLC_HTTP_DUPLICATE_ARG}" \
			2> >(grep -Ev "${VLC_STDERR_FILTER}" >&2)
		log INFO "VLC exited with code $?"
	fi
}

function log {
	local level=$1
	shift
	echo "[$(date '+%Y-%m-%d %H:%M:%S')] [${level}] $*"
}

function checkCommandExists {
	command -v "${1}" >/dev/null 2>&1 || { msg="I require ${1} but it's not installed. Aborting."; displayErrorMessage "${2}" "$msg" ;}
}

function displayErrorMessage {
	log ERROR "[${1}] ${2}"
	exit "$1"
}


# /dev/videoN is a character device, not a regular file; -f would always return false here.
if [ -c "${WEBCAM_DEVICE}" ] ; then
	VLC_C920_STREAM "${VIDEO_DEVICE_NB}" "${HTTP_PORT}" "${MOVIES_FOLDER}"
else
	message="Device ${WEBCAM_DEVICE} required but could not be found. Aborting."
	displayErrorMessage "${ERROR_WEBCAM_DOES_NOT_EXIST}" "${message}"
fi

# ] <-- needed because of Argbash
